Add images to tensorboard
mila-iqia/cookiecutter-pyml pull request #87
Opened 2022-11-28 20:28 UTC by jerpint

Adds support to plot images of the first batch of the validation set to tensorboard

![image](https://user-images.githubusercontent.com/18450628/204374513-5d4e410f-4ff0-4331-9bcb-59a733a63a14.png)

2022-11-28 21:04 UTC, mirkobronzimila commented
@jerpint : still have to check this PR (and some of the others), but I was wondering if we are getting too specific on the current toy task (like, here we assume we will work with images).
In the end, the toy task will be erased in the first week or work (or something like that), to make space for the real task.
But again, not sure if this PR is also doing more stuff.. I will be back later on this PR.

2022-11-28 21:39 UTC, jerpint commented
This PR uses a callback to show how to log an image to tensorboard, so it can easily be removed by simply removing the callback, and consulted to find out how to do it, but good point, we don't want to overdo it either. Not sure what the best tradeoff would be

2022-11-30 14:42 UTC, mirkobronzi commented
> This PR uses a callback to show how to log an image to tensorboard, so it can easily be removed by simply removing the callback, and consulted to find out how to do it, but good point, we don't want to overdo it either. Not sure what the best tradeoff would be

this is a perfect example for code logic that should be in the new repository that we will create.
So it does not weight on the cookiecutter, but it's still available.
Do you see any disadvantages with that?

2022-11-30 18:43 UTC, jerpint commented
Once we have cookiecutter in a stable state, i will probably maintain a separate repo with a bunch of killer features

2022-12-14 16:08 UTC, marondeau-mila requested changes
The only comments that matter are for `callbacks.py`, but I think they should be addressed before merging.

2022-12-14 16:08 UTC, marondeau-mila commented on {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/main.py
>  from {{cookiecutter.project_slug}}.models.model_loader import load_model
This is about line 64, because Github: This whole copying into a temp folder should be done in `DataModule.prepare_data`, so that it is only done once, on rank 0, during multi-gpu training.

2024-09-11 19:35 UTC, jerpint commented
stale, closing

2024-09-11 19:35 UTC, closed without merging