remove cookie-cutter dependency
mila-iqia/cookiecutter-pyml pull request #96
Opened 2022-12-14 18:57 UTC by jerpint

we remove the top-level cookiecutter instructions and migrate the project to `amlrt_project` instead

2022-12-14 19:15 UTC, marondeau-mila approved these changes

2022-12-14 19:15 UTC, marondeau-mila commented on README.md
> +    pip install -e .
Explain that this will be a development install, where you can modify directly the source, not a build/system/env install, where the package is placed in a site-package independent of the source.

2022-12-14 19:15 UTC, marondeau-mila commented on README.md
> +    cd .git/hooks/ && ln -s ../../hooks/pre-commit . && cd -
This should be `(cd .git/hooks/ && ln -s ../../hooks/pre-commit .)`

2022-12-14 19:15 UTC, marondeau-mila commented on docs/conf.py
> +copyright = '2020, amlrt_team'
We are in 2022, about to become 2023.

2022-12-14 19:53 UTC, jerpint commented on docs/conf.py
> +copyright = '2020, amlrt_team'
wow time moves fast 😹

2022-12-14 20:15 UTC, marondeau-mila approved these changes

2022-12-16 20:47 UTC, mirkobronzi commented
@jerpint : I do not think I will have the time necessary to review this code.
I do agree with @marondeau-mila that a general review can be enough..
To be safe, I would remove my review request, and add @hbertrand .
Two positive opinions will be enough to merge (so we speed up this PR).

2022-12-20 15:48 UTC, hbertrand requested changes
We should have a script to rename all the amlrt_project, amlrt_team and amlrt_email at once.

2022-12-20 15:48 UTC, hbertrand commented on .github/workflows/ci.yml
>        - master
so we have main AND master ?

2022-12-20 15:48 UTC, hbertrand commented on LICENSE
> +Copyright (c) {% now 'local', '%Y' %}, amlrt_team
shouldn't it be 2020 - CURRENT YEAR ?

2022-12-21 15:01 UTC, jerpint commented on .github/workflows/ci.yml
>        - master
indeed, new projects should only have main from now on, not master, as this is deprecated on github

2022-12-21 17:56 UTC, jerpint commented on setup.py
> +    install_requires=[
no it was already there to begin with, could be nice to remove setup.py altogether in a new pull request and put everything in requirements.txt, we have an issue for this in https://github.com/mila-iqia/cookiecutter-pyml/issues/90

2022-12-21 17:56 UTC, jerpint commented on LICENSE
> +Copyright (c) {% now 'local', '%Y' %}, amlrt_team
perhaps we can simply remove the year altogether? Note sure if it matters

2022-12-21 17:57 UTC, jerpint commented on LICENSE
> +Copyright (c) {% now 'local', '%Y' %}, amlrt_team
I'll set it to 2023 for now

2023-01-17 15:08 UTC, hbertrand approved these changes

2023-01-17 22:16 UTC, merged